### VarianceThreshold

In [14]:
import numpy as np

# 宣告X變數為6*3的向量
X = np.array([[0, 0, 1], 
              [0, 1, 0], 
              [1, 0, 0], 
              [0, 1, 1], 
              [0, 1, 0], 
              [0, 1, 1]])
print(X)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]]


In [11]:
# 計算出X向量各直行的變異數
np.var(X, axis=0)

array([0.13888889, 0.22222222, 0.25      ])

In [12]:
from sklearn.feature_selection import VarianceThreshold

# 設定只保留各直行中變異數大於.8*.2的元素
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
# 因第一行的元素為約.14
# 理當小於閥值threshold.16
# 因此去除該直行
sel.fit_transform(X)

array([[0, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1]])