### VarianceThreshold

In [2]:
import numpy as np

# 宣告X變數為6*3的向量
X = np.array([[0, 0, 1], 
              [0, 1, 0], 
              [1, 0, 0], 
              [0, 1, 1], 
              [0, 1, 0], 
              [0, 1, 1]])
print(X)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]]


In [3]:
# 計算出X向量各直行的變異數
np.var(X, axis=0)

array([0.13888889, 0.22222222, 0.25      ])

In [4]:
from sklearn.feature_selection import VarianceThreshold

# 設定只保留各直行中變異數大於.8*.2的元素
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
# 因第一行的元素為約.14
# 理當小於閥值threshold.16
# 因此去除該直行
sel.fit_transform(X)

array([[0, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1]])



---



---



---



### RFE

In [14]:
from sklearn.datasets import load_boston
from sklearn.ensemble import RandomForestRegressor

import warnings
warnings.simplefilter("ignore")

boston = load_boston()
X = boston['data']
y = boston['target']
names = boston['feature_names']

rf = RandomForestRegressor()
rf.fit(X, y)

print('Features importance:\n')

for name, importance in sorted(zip(map(lambda x: round(x, 4), rf.feature_importances_), names), reverse=True):
    print(name, importance)

Features importance:

0.4212 RM
0.3791 LSTAT
0.0683 DIS
0.0419 CRIM
0.0222 NOX
0.0185 PTRATIO
0.0138 TAX
0.0129 AGE
0.0111 B
0.0059 INDUS
0.0033 RAD
0.001 ZN
0.0008 CHAS
